# -*- coding: utf-8 -*-
"""Rainfall vs production and yield.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1InkEwIYQdjfEjTc-HhJLGYimazMOlp04

Data Loading and Preparation
"""

# Install, import, load and prepare data
!pip install gspread pandas

from google.colab import auth
from google.auth import default
import gspread
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Authenticate and load from Google Sheets
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

worksheet = gc.open('Final_maize_production_yield_climate_dataset').sheet1
data = worksheet.get_all_values()
df = pd.DataFrame(data[1:], columns=data[0])

# Clean and rename columns
df = df.rename(columns={
    'season_year': 'Year',
    'rfh_total': 'Rainfall_raw',
    'yield': 'Yield_t_ha',
    'production': 'Production_tons'
})

# Convert to numeric
numeric_cols = ['Year', 'Rainfall_raw', 'Yield_t_ha', 'Production_tons']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Drop rows with missing values
df = df.dropna(subset=['Province', 'Year'])
df['Year'] = df['Year'].astype(int)

# Convert rainfall from 1000x scale to actual mm
df['Rainfall_mm'] = df['Rainfall_raw'] / 1000
df = df.drop(columns=['Rainfall_raw'])

# Muchinga with data from 2011 onwards
df = df[~((df['Province'] == 'Muchinga') & (df['Year'] < 2011))]

# FHandle missing yield data for 2008-2010
df = df.dropna(subset=['Yield_t_ha'])
print(f"Removed rows with missing yield data")

# Create analysis datasets
df_analysis = df[df['Province'] != 'Muchinga'].copy()
df_full = df.copy()  # For Tableau

# Verify data structure
print("-" * 50)
print("DATA LOADED SUCCESSFULLY")
print("-" * 50)
print(f"Total rows: {df.shape[0]}")
print(f"Years: {df['Year'].min()}-{df['Year'].max()}")
print(f"Provinces: {df['Province'].nunique()}")
print(f"Rainfall range: {df['Rainfall_mm'].min():.0f} - {df['Rainfall_mm'].max():.0f} mm")
print(f"Yield range: {df['Yield_t_ha'].min():.2f} - {df['Yield_t_ha'].max():.2f} t/ha")

print("\nPROVINCE BREAKDOWN")
print("-" * 40)
for province in sorted(df['Province'].unique()):
    province_data = df[df['Province'] == province]
    years = sorted(province_data['Year'].unique())
    year_range = f"{min(years)}-{max(years)}"

    if province == 'Muchinga':
        expected = 3
        note = "[EXCLUDED FROM ANALYSIS]"
    else:
        expected = 24
        note = ""

    status = "✓" if len(years) == expected else f" ({len(years)} years, expected {expected})"
    print(f"{province}: {len(years)} years ({year_range}) {status} {note}")

print("\nANALYSIS DATASET")
print("-" * 40)
print(f"Provinces: {df_analysis['Province'].nunique()}")
print(f"Rows: {df_analysis.shape[0]}")
print(f"Rainfall in analysis: {df_analysis['Rainfall_mm'].mean():.0f} mm (mean)")

# Quick check of analysis data
print("\n ANALYSIS DATASET PREVIEW")
print("-" * 40)
print(df_analysis[['Province', 'Year', 'Rainfall_mm', 'Yield_t_ha']].head(10))

"""Exploratory Data Analysis"""

print("-" * 50)
print("EXPLORATORY DATA ANALYSIS - ALL 9 PROVINCES")
print("-" * 50)

# Summary statistics for all provinces
print("\nOVERALL SUMMARY STATISTICS")
print("-" * 40)
print(f"Rainfall (mm): mean={df_analysis['Rainfall_mm'].mean():.1f}, min={df_analysis['Rainfall_mm'].min():.1f}, max={df_analysis['Rainfall_mm'].max():.1f}")
print(f"Yield (t/ha): mean={df_analysis['Yield_t_ha'].mean():.2f}, min={df_analysis['Yield_t_ha'].min():.2f}, max={df_analysis['Yield_t_ha'].max():.2f}")
print(f"Production (tons): mean={df_analysis['Production_tons'].mean():.0f}, min={df_analysis['Production_tons'].min():.0f}, max={df_analysis['Production_tons'].max():.0f}")

# Summary by province
print("\nSUMMARY BY PROVINCE")
print("-" * 50)
province_summary = df_analysis.groupby('Province').agg({
    'Rainfall_mm': ['mean', 'min', 'max', 'std'],
    'Yield_t_ha': ['mean', 'min', 'max', 'std'],
    'Production_tons': ['mean', 'sum']
}).round(2)

# Flatten column names for better display
province_summary.columns = ['_'.join(col).strip() for col in province_summary.columns.values]
print(province_summary)

# Distribution plots for ALL provinces
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Rainfall distribution
df_analysis['Rainfall_mm'].hist(bins=20, ax=axes[0,0], color='steelblue', edgecolor='black')
axes[0,0].set_title('Rainfall Distribution - All Provinces')
axes[0,0].set_xlabel('Rainfall (mm)')
axes[0,0].set_ylabel('Frequency')

# Yield distribution
df_analysis['Yield_t_ha'].hist(bins=20, ax=axes[0,1], color='forestgreen', edgecolor='black')
axes[0,1].set_title('Yield Distribution - All Provinces')
axes[0,1].set_xlabel('Yield (t/ha)')
axes[0,1].set_ylabel('Frequency')

# Rainfall by province
df_analysis.boxplot(column='Rainfall_mm', by='Province', ax=axes[1,0], rot=45)
axes[1,0].set_title('Rainfall Distribution by Province')
axes[1,0].set_xlabel('Province')
axes[1,0].set_ylabel('Rainfall (mm)')

# Yield by province
df_analysis.boxplot(column='Yield_t_ha', by='Province', ax=axes[1,1], rot=45)
axes[1,1].set_title('Yield Distribution by Province')
axes[1,1].set_xlabel('Province')
axes[1,1].set_ylabel('Yield (t/ha)')

plt.suptitle('')
plt.tight_layout()
plt.show()

"""Trend Analysis"""

print("-" * 50)
print("TREND ANALYSIS - ALL PROVINCES")
print("-" * 50)

# Yearly trends (national averages)
yearly_national = df_analysis.groupby('Year').agg({
    'Rainfall_mm': 'mean',
    'Yield_t_ha': 'mean',
    'Production_tons': 'sum'
}).reset_index()

fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# National rainfall trend
axes[0,0].plot(yearly_national['Year'], yearly_national['Rainfall_mm'], 'o-', color='steelblue')
axes[0,0].set_title('National Average Rainfall Over Time')
axes[0,0].set_xlabel('Year')
axes[0,0].set_ylabel('Rainfall (mm)')
axes[0,0].grid(True, alpha=0.3)

# National yield trend
axes[0,1].plot(yearly_national['Year'], yearly_national['Yield_t_ha'], 'o-', color='forestgreen')
axes[0,1].set_title('National Average Yield Over Time')
axes[0,1].set_xlabel('Year')
axes[0,1].set_ylabel('Yield (t/ha)')
axes[0,1].grid(True, alpha=0.3)

# National production trend
axes[1,0].plot(yearly_national['Year'], yearly_national['Production_tons']/1e6, 'o-', color='darkorange')
axes[1,0].set_title('Total National Production Over Time')
axes[1,0].set_xlabel('Year')
axes[1,0].set_ylabel('Production (million tons)')
axes[1,0].grid(True, alpha=0.3)

# Yield trends by province(9)
for province in sorted(df_analysis['Province'].unique()):
    province_data = df_analysis[df_analysis['Province'] == province]
    axes[1,1].plot(province_data['Year'], province_data['Yield_t_ha'], 'o-', label=province, alpha=0.7)
axes[1,1].set_title('Yield Trends by Province - ALL 9')
axes[1,1].set_xlabel('Year')
axes[1,1].set_ylabel('Yield (t/ha)')
axes[1,1].legend(loc='best', fontsize=8)
axes[1,1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print("\nTREND SUMMARY")
print("-" * 40)
print(f"National rainfall: Highly variable, no clear trend")
print(f"National yield: {yearly_national[yearly_national['Year']==1986]['Yield_t_ha'].values[0]:.2f} t/ha (1986) → {yearly_national[yearly_national['Year']==2013]['Yield_t_ha'].values[0]:.2f} t/ha (2013)")
print(f"Production peak: {yearly_national['Production_tons'].max()/1e6:.1f} million tons")

"""Correlation Analysis"""

print("-" * 60)
print("CORRELATION ANALYSIS - ALL PROVINCES")
print("-" * 60)

# Overall correlation
corr_rain_yield = df_analysis['Rainfall_mm'].corr(df_analysis['Yield_t_ha'])
corr_rain_prod = df_analysis['Rainfall_mm'].corr(df_analysis['Production_tons'])

print(f"Overall Rainfall-Yield correlation: {corr_rain_yield:.3f}")
print(f"Overall Rainfall-Production correlation: {corr_rain_prod:.3f}")

# Correlation by province
print("\nCORRELATION BY PROVINCE")
print("-" * 40)
corr_by_province = df_analysis.groupby('Province').apply(
    lambda x: x['Rainfall_mm'].corr(x['Yield_t_ha'])
).round(3)
for province, corr in corr_by_province.items():
    print(f"{province}: {corr}")

# Visualize relationship
fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# Scatter plot
axes[0].scatter(df_analysis['Rainfall_mm'], df_analysis['Yield_t_ha'], alpha=0.5)
axes[0].set_xlabel('Rainfall (mm)')
axes[0].set_ylabel('Yield (t/ha)')
axes[0].set_title('Rainfall vs Yield - All Provinces Combined')

# Add trend line
z = np.polyfit(df_analysis['Rainfall_mm'], df_analysis['Yield_t_ha'], 1)
p = np.poly1d(z)
axes[0].plot(sorted(df_analysis['Rainfall_mm']), p(sorted(df_analysis['Rainfall_mm'])), "r--", alpha=0.8, label=f'trend (r={corr_rain_yield:.2f})')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Scatter by province
provinces = sorted(df_analysis['Province'].unique())
colors = plt.cm.tab20(np.linspace(0, 1, len(provinces)))

for i, province in enumerate(provinces):
    prov_data = df_analysis[df_analysis['Province'] == province]
    axes[1].scatter(prov_data['Rainfall_mm'], prov_data['Yield_t_ha'],
                   color=colors[i], label=province, alpha=0.6)
axes[1].set_xlabel('Rainfall (mm)')
axes[1].set_ylabel('Yield (t/ha)')
axes[1].set_title('Rainfall vs Yield - Colored by Province')
axes[1].legend(loc='best', fontsize=8)
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""Rainfall Efficiency by Province"""

print("-" * 50)
print("RAINFALL EFFICIENCY - ALL PROVINCES")
print("-" * 50)

# Calculate efficiency (yield per 100mm rain)
df_analysis = df_analysis.copy()
df_analysis.loc[:, 'Rain_efficiency'] = df_analysis['Yield_t_ha'] / (df_analysis['Rainfall_mm']/100)

efficiency_all = df_analysis.groupby('Province')['Rain_efficiency'].agg(['mean', 'std', 'min', 'max']).round(3)
efficiency_all = efficiency_all.sort_values('mean', ascending=False)

print("RAINFALL EFFICIENCY (tons/ha per 100mm rain)")
print("-" * 60)
print(efficiency_all)

# Visualize
plt.figure(figsize=(12, 6))
colors_efficiency = plt.cm.RdYlGn(np.linspace(0.3, 0.9, len(efficiency_all)))
bars = plt.bar(efficiency_all.index, efficiency_all['mean'], color=colors_efficiency, alpha=0.8)
plt.errorbar(efficiency_all.index, efficiency_all['mean'], yerr=efficiency_all['std'],
             fmt='none', color='black', capsize=5)

plt.title('Rainfall Efficiency by Province - ALL 9', fontsize=14)
plt.xlabel('Province')
plt.ylabel('Yield per 100mm rain (t/ha)')
plt.axhline(y=efficiency_all['mean'].mean(), color='red', linestyle='--',
            alpha=0.5, label=f'National average ({efficiency_all["mean"].mean():.3f})')
plt.legend()
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()

print(f"\nMost efficient: {efficiency_all.index[0]} ({efficiency_all.iloc[0]['mean']:.3f} t/ha per 100mm)")
print(f"Least efficient: {efficiency_all.index[-1]} ({efficiency_all.iloc[-1]['mean']:.3f} t/ha per 100mm)")
print(f"Efficiency gap: {(efficiency_all.iloc[0]['mean'] / efficiency_all.iloc[-1]['mean'] - 1)*100:.0f}% difference")

"""Optimal Rainfall Range Analysis"""

print("-" * 50)
print("OPTIMAL RAINFALL RANGE - ALL PROVINCES")
print("-" * 50)

# Show rainfall distribution
print("\nRAINFALL DISTRIBUTION SUMMARY")
print("-" * 50)
print(df_analysis['Rainfall_mm'].describe())

# Create bins
df_analysis.loc[:, 'Rain_bin'] = pd.cut(df_analysis['Rainfall_mm'],
                                         bins=[0, 800, 1000, 1200, 1400, 1600, 3000],
                                         labels=['<800', '800-1000', '1000-1200', '1200-1400', '1400-1600', '1600+'])

bin_summary = df_analysis.groupby('Rain_bin', observed=False)['Yield_t_ha'].agg(['mean', 'count', 'std']).round(2)

print("\nAVERAGE YIELD BY RAINFALL RANGE")
print("-" * 40)
print(bin_summary)

# Visualize
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Bar chart
axes[0].bar(bin_summary.index, bin_summary['mean'],
           color=['darkred', 'orange', 'green', 'green', 'green', 'lightgreen'],
           alpha=0.8, yerr=bin_summary['std'], capsize=5)
axes[0].axhline(y=df_analysis['Yield_t_ha'].mean(), color='red', linestyle='--',
                label=f'Overall average ({df_analysis["Yield_t_ha"].mean():.2f} t/ha)')
axes[0].set_title('Yield by Rainfall Range - All Provinces')
axes[0].set_xlabel('Rainfall Range (mm)')
axes[0].set_ylabel('Average Yield (t/ha)')
axes[0].legend()
axes[0].grid(True, alpha=0.3, axis='y')
axes[0].tick_params(axis='x', rotation=45)

# Distribution of observations by range
axes[1].pie(bin_summary['count'], labels=bin_summary.index, autopct='%1.1f%%',
           colors=['darkred', 'orange', 'green', 'green', 'green', 'lightgreen'])
axes[1].set_title('Distribution of Observations by Rainfall Range')

plt.tight_layout()
plt.show()

# Find optimal range
valid_bins = bin_summary[bin_summary['count'] >= 5]
if len(valid_bins) > 0:
    optimal = valid_bins['mean'].idxmax()
    print(f"\nOPTIMAL RANGE: {optimal} mm")
    print(f"Average yield in optimal range: {valid_bins.loc[optimal, 'mean']} t/ha")
    print(f"Observations in optimal range: {valid_bins.loc[optimal, 'count']} ({valid_bins.loc[optimal, 'count']/bin_summary['count'].sum()*100:.1f}% of data)")

"""Climate Variability / Risk Analysis"""

print("-" * 50)
print("CLIMATE VARIABILITY / RISK ANALYSIS")
print("-" * 50)

# Calculate percentiles
percentiles = df_analysis['Rainfall_mm'].quantile([0.1, 0.25, 0.5, 0.75, 0.9]).round(0)
print("\nRAINFALL PERCENTILES")
print("-" * 40)
print(f"10th percentile: {percentiles[0.1]:.0f} mm")
print(f"25th percentile: {percentiles[0.25]:.0f} mm")
print(f"50th percentile (median): {percentiles[0.5]:.0f} mm")
print(f"75th percentile: {percentiles[0.75]:.0f} mm")
print(f"90th percentile: {percentiles[0.9]:.0f} mm")

# Define extreme years
low_threshold = percentiles[0.25]
high_threshold = percentiles[0.75]

low_rain = df_analysis[df_analysis['Rainfall_mm'] <= low_threshold]
normal_rain = df_analysis[(df_analysis['Rainfall_mm'] > low_threshold) & (df_analysis['Rainfall_mm'] < high_threshold)]
high_rain = df_analysis[df_analysis['Rainfall_mm'] >= high_threshold]

print(f"\nTHRESHOLDS")
print("-" * 40)
print(f"Low rainfall years: ≤ {low_threshold:.0f} mm ({len(low_rain)} rows, {len(low_rain)/len(df_analysis)*100:.1f}%)")
print(f"Normal years: {low_threshold:.0f}-{high_threshold:.0f} mm ({len(normal_rain)} rows, {len(normal_rain)/len(df_analysis)*100:.1f}%)")
print(f"High rainfall years: ≥ {high_threshold:.0f} mm ({len(high_rain)} rows, {len(high_rain)/len(df_analysis)*100:.1f}%)")

# Calculate yields in extreme years
extreme_summary = pd.DataFrame({
    'Category': ['Low Rain Years', 'Normal Years', 'High Rain Years'],
    'Count': [len(low_rain), len(normal_rain), len(high_rain)],
    'Mean Yield': [low_rain['Yield_t_ha'].mean(), normal_rain['Yield_t_ha'].mean(), high_rain['Yield_t_ha'].mean()],
    'Std Yield': [low_rain['Yield_t_ha'].std(), normal_rain['Yield_t_ha'].std(), high_rain['Yield_t_ha'].std()]
}).round(2)

print("\nYIELD IN EXTREME RAINFALL YEARS")
print("-" * 40)
print(extreme_summary.to_string(index=False))

# Calculate percent differences
normal_yield = extreme_summary.loc[1, 'Mean Yield']
if not pd.isna(extreme_summary.loc[0, 'Mean Yield']):
    low_diff = ((extreme_summary.loc[0, 'Mean Yield'] / normal_yield - 1) * 100)
    print(f"\nLow rain years: {low_diff:.0f}% vs normal")
if not pd.isna(extreme_summary.loc[2, 'Mean Yield']):
    high_diff = ((extreme_summary.loc[2, 'Mean Yield'] / normal_yield - 1) * 100)
    print(f"High rain years: {high_diff:.0f}% vs normal")

# Low rainfall years by province
low_rain_provinces = low_rain.groupby('Province').size().sort_values(ascending=False)

plt.figure(figsize=(12, 6))
colors_risk = plt.cm.Reds(np.linspace(0.4, 0.9, len(low_rain_provinces)))
low_rain_provinces.plot(kind='bar', color=colors_risk)
plt.title(f'Low Rainfall Years (≤{low_threshold:.0f}mm) by Province - ALL 9')
plt.xlabel('Province')
plt.ylabel('Number of years')
plt.axhline(y=low_rain_provinces.mean(), color='navy', linestyle='--',
            label=f'Average ({low_rain_provinces.mean():.1f} years)')
plt.legend()
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()

print(f"\nVULNERABILITY RANKING")
print("-" * 40)
for i, (province, count) in enumerate(low_rain_provinces.items(), 1):
    print(f"{i}. {province}: {count} low-rainfall years")

"""Basic Modeling"""

import statsmodels.api as sm

print("-" * 50)
print("REGRESSION ANALYSIS")
print("-" * 50)

# Linear model
X = sm.add_constant(df_analysis['Rainfall_mm'])
y = df_analysis['Yield_t_ha']
model = sm.OLS(y, X).fit()

# Quadratic model
df_analysis.loc[:, 'Rainfall_sq'] = df_analysis['Rainfall_mm']**2
X2 = sm.add_constant(df_analysis[['Rainfall_mm', 'Rainfall_sq']])
model2 = sm.OLS(y, X2).fit()

print(f"Linear model R²: {model.rsquared:.3f}")
print(f"Quadratic model R²: {model2.rsquared:.3f}")

print("\nMODEL COEFFICIENTS")
print("-" * 40)
print("Linear model:")
print(f"  Intercept: {model.params.iloc[0]:.4f}")
print(f"  Rainfall coefficient: {model.params.iloc[1]:.6f}")

print("\nQuadratic model:")
print(f"  Intercept: {model2.params.iloc[0]:.4f}")
print(f"  Rainfall: {model2.params.iloc[1]:.6f}")
print(f"  Rainfall²: {model2.params.iloc[2]:.6f}")

# Model by province
print("\nMODEL BY PROVINCE")
print("-" * 40)
province_models = []
for province in sorted(df_analysis['Province'].unique()):
    prov_data = df_analysis[df_analysis['Province'] == province]
    if len(prov_data) > 5:  # Need minimum observations
        X_prov = sm.add_constant(prov_data['Rainfall_mm'])
        y_prov = prov_data['Yield_t_ha']
        prov_model = sm.OLS(y_prov, X_prov).fit()
        province_models.append({
            'Province': province,
            'R²': prov_model.rsquared,
            'Coefficient': prov_model.params.iloc[1],
            'P-value': prov_model.pvalues.iloc[1]
        })

prov_model_df = pd.DataFrame(province_models).round(3)
print(prov_model_df.to_string(index=False))

# Visualize the weak relationship
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.scatter(df_analysis['Rainfall_mm'], df_analysis['Yield_t_ha'], alpha=0.3, s=30)
# Add lowess smoother
from scipy import stats
x_sorted = np.sort(df_analysis['Rainfall_mm'].unique())
y_mean = df_analysis.groupby('Rainfall_mm')['Yield_t_ha'].mean()
plt.plot(y_mean.index, y_mean.values, 'r-', linewidth=2, label='Average by rainfall')
plt.xlabel('Rainfall (mm)')
plt.ylabel('Yield (t/ha)')
plt.title(f'Rainfall vs Yield (R² = {model.rsquared:.3f})')
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
# Residuals plot
residuals = model.resid
plt.scatter(model.fittedvalues, residuals, alpha=0.5)
plt.axhline(y=0, color='r', linestyle='--')
plt.xlabel('Fitted values')
plt.ylabel('Residuals')
plt.title('Residual Plot')
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()