# -*- coding: utf-8 -*-
"""Rfq rainfall.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QzF5Dd3Xbq8Ud8lRNNsJh0HyKjn8vFsI
"""

!pip install gspread pandas google-auth

import pandas as pd
import numpy as np
import gspread
from google.colab import auth
from google.auth import default
import matplotlib.pyplot as plt

# Authenticate with Google
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)
sheet_name = "rainfall_analysis_rf_rfq"
try:
    spreadsheet = gc.open(sheet_name)
    worksheet = spreadsheet.get_worksheet(0)
    print(f"   Worksheet name: {worksheet.title}")

    # Load all data
    data = worksheet.get_all_values()
    df = pd.DataFrame(data[1:], columns=data[0])

    print(f" Loaded {len(df)} rows with {len(df.columns)} columns")

except Exception as e:
    print(f" Error opening spreadsheet: {e}")

numeric_columns = ['Year', 'Month', 'rfh', 'rfq']
for col in numeric_columns:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

# Remove rows with missing critical data
df = df.dropna(subset=['rfq', 'Year', 'Month'])

print(f"\n After cleaning: {len(df)} rows")

LOW_PERCENTILE = 30  # Bottom 30% = Low rainfall
HIGH_PERCENTILE = 70  # Top 30% = High rainfall

print(f"\nClassification thresholds:")
print(f"  - Low rainfall: Below {LOW_PERCENTILE}th percentile")
print(f"  - High rainfall: Above {HIGH_PERCENTILE}th percentile")
print(f"  - Normal rainfall: Between these values")

# Global thresholds
global_low = np.percentile(df['rfq'].dropna(), LOW_PERCENTILE)
global_high = np.percentile(df['rfq'].dropna(), HIGH_PERCENTILE)

print(f"\n=== GLOBAL THRESHOLDS ===")
print(f"Low threshold: {global_low:.2f}")
print(f"High threshold: {global_high:.2f}")

# Province-specific thresholds
province_thresholds = df.groupby('Province')['rfq'].agg([
    ('low_threshold', lambda x: np.percentile(x.dropna(), LOW_PERCENTILE)),
    ('high_threshold', lambda x: np.percentile(x.dropna(), HIGH_PERCENTILE))
]).reset_index()

print(f"\n=== PROVINCE THRESHOLDS ===")
print(province_thresholds)

# Province + Month-specific thresholds
monthly_thresholds = df.groupby(['Province', 'Month'])['rfq'].agg([
    ('low_threshold', lambda x: np.percentile(x.dropna(), LOW_PERCENTILE)),
    ('high_threshold', lambda x: np.percentile(x.dropna(), HIGH_PERCENTILE))
]).reset_index()

print(f"\n=== MONTHLY THRESHOLDS ===")
print(monthly_thresholds.head(10))

df_classified = df.copy()

# Global
df_classified['rainfall_class_global'] = 'Normal'
df_classified.loc[df_classified['rfq'] < global_low, 'rainfall_class_global'] = 'Low'
df_classified.loc[df_classified['rfq'] > global_high, 'rainfall_class_global'] = 'High'

# Monthly
df_classified = df_classified.merge(monthly_thresholds, on=['Province', 'Month'], how='left')
df_classified['rainfall_class_monthly'] = 'Normal'
df_classified.loc[df_classified['rfq'] < df_classified['low_threshold'], 'rainfall_class_monthly'] = 'Low' # Corrected from low_threshold_y
df_classified.loc[df_classified['rfq'] > df_classified['high_threshold'], 'rainfall_class_monthly'] = 'High' # Corrected from high_threshold_y

df_classified = df_classified.rename(columns={
    'low_threshold': 'low_threshold_monthly',
    'high_threshold': 'high_threshold_monthly'
})


print("\n=== CLASSIFICATION DISTRIBUTION ===")
print("\nGlobal Classification:")
print(df_classified['rainfall_class_global'].value_counts())
print(f"\n{df_classified['rainfall_class_global'].value_counts(normalize=True) * 100}")


print("\nMonthly Classification :")
print(df_classified['rainfall_class_monthly'].value_counts())
print(f"\n{df_classified['rainfall_class_monthly'].value_counts(normalize=True) * 100}")

# Create a new sheet with classified data
try:
    try:
        classified_worksheet = spreadsheet.worksheet("Classified_Data")
        print(f"\nWorksheet 'Classified_Data' already exists. Clearing and updating...")
        classified_worksheet.clear()
    except gspread.exceptions.WorksheetNotFound:
        classified_worksheet = spreadsheet.add_worksheet(title="Classified_Data", rows=1000, cols=20)
        print(f"\n Created new sheet: 'Classified_Data'")

    # Convert DataFrame to list for uploading
    classified_data = [df_classified.columns.tolist()] + df_classified.astype(str).values.tolist()
    classified_worksheet.update(classified_data, value_input_option='USER_ENTERED')
    print(f" Saved classified data to sheet: 'Classified_Data'")


    try:
        thresholds_worksheet = spreadsheet.worksheet("Thresholds")
        print(f"Worksheet 'Thresholds' already exists. Clearing and updating...")
        thresholds_worksheet.clear()
    except gspread.exceptions.WorksheetNotFound:
        thresholds_worksheet = spreadsheet.add_worksheet(title="Thresholds", rows=1000, cols=10)
        print(f" Created new sheet: 'Thresholds'")

    thresholds_data = [monthly_thresholds.columns.tolist()] + monthly_thresholds.astype(str).values.tolist()
    thresholds_worksheet.update(thresholds_data, value_input_option='USER_ENTERED')
    print(f" Saved thresholds to sheet: 'Thresholds'")

except Exception as e:
    print(f" Could not create or update sheets: {e}")

# Create a quick plot to see classification over time
plt.figure(figsize=(15, 6))

# Sample one province for visualization
sample_province = df_classified['Province'].unique()[0]
sample_data = df_classified[df_classified['Province'] == sample_province].copy()
sample_data['Date'] = pd.to_datetime(sample_data['Year'].astype(str) + '-' + sample_data['Month'].astype(str), format='%Y-%m')
sample_data = sample_data.sort_values('Date')

# Color mapping
color_map = {'Low': 'red', 'Normal': 'green', 'High': 'blue'}
colors = sample_data['rainfall_class_monthly'].map(color_map)

plt.scatter(sample_data['Date'], sample_data['rfq'], c=colors, alpha=0.6, s=20)
plt.title(f'Rainfall Classification - {sample_province} (Monthly Method)')
plt.xlabel('Date')
plt.ylabel('rfq')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Exploring monthly rainfall

# check provinces
print(" ALL PROVINCES IN DATA \n")
provinces = sorted(df_classified['Province'].unique())
print(f"Total provinces: {len(provinces)}")
print(provinces)

# Check if Muchinga is included
if 'Muchinga' in provinces:
    print("\n Muchinga province is included (limited data: 2011-2013 only)")


# Filter out Muchinga
provinces_to_plot = [p for p in provinces if p != 'Muchinga']  # Exclude Muchinga
print(f"\nProvinces to plot: {len(provinces_to_plot)}")

print("\n MONTHLY RAINFALL STATISTICS ")
monthly_stats = df_classified.groupby('Month')['rfq'].agg(['count', 'mean', 'std', 'min', 'max']).round(2)
print(monthly_stats)


fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# Boxplot by month
df_classified.boxplot(column='rfq', by='Month', ax=axes[0,0])
axes[0,0].set_title('Monthly Rainfall Distribution (All Provinces)')
axes[0,0].set_xlabel('Month')
axes[0,0].set_ylabel('rfq')
axes[0,0].grid(True, alpha=0.3)

# Mean rainfall by month with error bars
monthly_means = df_classified.groupby('Month')['rfq'].mean()
monthly_std = df_classified.groupby('Month')['rfq'].std()
axes[0,1].bar(monthly_means.index, monthly_means.values, yerr=monthly_std.values,
              capsize=5, alpha=0.7, color='steelblue')
axes[0,1].set_title('Average Monthly Rainfall (±1 Std Dev)')
axes[0,1].set_xlabel('Month')
axes[0,1].set_ylabel('Mean rfq')
axes[0,1].grid(True, alpha=0.3)

# Time series of monthly rainfall
key_months = [10, 11, 12, 1, 2, 3]
for month in key_months:
    month_data = df_classified[df_classified['Month'] == month]
    monthly_avg = month_data.groupby('Year')['rfq'].mean()
    axes[1,0].plot(monthly_avg.index, monthly_avg.values,
                   label=f'Month {month}', alpha=0.7, linewidth=1.5)
axes[1,0].set_title('Rainfall Trends by Month (Growing Season)')
axes[1,0].set_xlabel('Year')
axes[1,0].set_ylabel('rfq')
axes[1,0].legend()
axes[1,0].grid(True, alpha=0.3)

# Heatmap of mean rainfall by province-month
# Filter out Muchinga
df_for_heatmap = df_classified[df_classified['Province'] != 'Muchinga'] if 'Muchinga' in provinces else df_classified
pivot_rain = df_for_heatmap.pivot_table(values='rfq', index='Province', columns='Month', aggfunc='mean')
im = axes[1,1].imshow(pivot_rain.values, aspect='auto', cmap='YlGnBu')
axes[1,1].set_xticks(range(len(pivot_rain.columns)))
axes[1,1].set_xticklabels(pivot_rain.columns)
axes[1,1].set_yticks(range(len(pivot_rain.index)))
axes[1,1].set_yticklabels(pivot_rain.index)
axes[1,1].set_title('Average Rainfall by Province and Month (mm)')
plt.colorbar(im, ax=axes[1,1])

plt.tight_layout()
plt.show()

# provincial monthly patterns

print("\n PROVINCE-SPECIFIC MONTHLY PATTERNS \n")

# Calculate number of rows needed
n_provinces = len(provinces_to_plot)
n_cols = 3
n_rows = (n_provinces + n_cols - 1) // n_cols

fig, axes = plt.subplots(n_rows, n_cols, figsize=(15, 4 * n_rows))
axes = axes.flatten() if n_rows > 1 else [axes]

for idx, province in enumerate(provinces_to_plot):
    province_data = df_classified[df_classified['Province'] == province]

    # Calculate mean and std by month
    monthly_mean = province_data.groupby('Month')['rfq'].mean()
    monthly_std = province_data.groupby('Month')['rfq'].std()

    # Plot
    axes[idx].bar(monthly_mean.index, monthly_mean.values, yerr=monthly_std.values,
                  capsize=5, alpha=0.7, color='steelblue')
    axes[idx].set_title(f'{province}')
    axes[idx].set_xlabel('Month')
    axes[idx].set_ylabel('Mean rfq')
    axes[idx].set_xticks(range(1, 13))
    axes[idx].grid(True, alpha=0.3)
for idx in range(len(provinces_to_plot), len(axes)):
    axes[idx].set_visible(False)

plt.tight_layout()
plt.show()

# rainfall classification

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Distribution of classifications by month
class_by_month = pd.crosstab(df_classified['Month'], df_classified['rainfall_class_monthly'], normalize='index')
class_by_month.plot(kind='bar', stacked=True, ax=axes[0], color=['red', 'green', 'blue'], alpha=0.7)
axes[0].set_title('Rainfall Classification by Month')
axes[0].set_xlabel('Month')
axes[0].set_ylabel('Proportion')
axes[0].legend(title='Class')
axes[0].grid(True, alpha=0.3)

# Distribution of classifications by province (excluding Muchinga)
df_for_province = df_classified[df_classified['Province'] != 'Muchinga'] if 'Muchinga' in provinces else df_classified
class_by_province = pd.crosstab(df_for_province['Province'], df_for_province['rainfall_class_monthly'], normalize='index')
class_by_province.plot(kind='bar', stacked=True, ax=axes[1], color=['red', 'green', 'blue'], alpha=0.7)
axes[1].set_title('Rainfall Classification by Province')
axes[1].set_xlabel('Province')
axes[1].set_ylabel('Proportion')
axes[1].legend(title='Class')
axes[1].grid(True, alpha=0.3)
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# rainfall variability

# Calculate coefficient of variation by month and province
cv_data = df_classified[df_classified['Province'] != 'Muchinga'] if 'Muchinga' in provinces else df_classified
cv_by_month = cv_data.groupby(['Province', 'Month'])['rfq'].agg(
    lambda x: x.std() / x.mean() * 100 if x.mean() > 0 else 0
).reset_index()

print("\n RAINFALL VARIABILITY (Coefficient of Variation %) \n")
print("Most variable months by province:")
for province in sorted(cv_by_month['Province'].unique()):
    province_cv = cv_by_month[cv_by_month['Province'] == province]
    if not province_cv.empty:
        max_cv = province_cv.loc[province_cv['rfq'].idxmax()]
        print(f"{province:15s}: Most variable month = {max_cv['Month']:.0f} (CV = {max_cv['rfq']:.1f}%)")

# Heatmap of CV
pivot_cv = cv_by_month.pivot(index='Province', columns='Month', values='rfq')
plt.figure(figsize=(12, 8))
im = plt.imshow(pivot_cv.values, aspect='auto', cmap='RdYlBu_r')
plt.colorbar(im, label='Coefficient of Variation (%)')
plt.xticks(range(len(pivot_cv.columns)), pivot_cv.columns)
plt.yticks(range(len(pivot_cv.index)), pivot_cv.index)
plt.title('Rainfall Variability (CV%) by Province and Month')
plt.xlabel('Month')
plt.ylabel('Province')
plt.show()

# rainfall seasonal

# Define wet month (rfq > 50mm)
df_classified['Wet_Month'] = df_classified['rfq'] > 50

# Count wet months by province
wet_counts = df_classified.groupby(['Province', 'Year'])['Wet_Month'].sum().reset_index()
wet_counts_avg = wet_counts.groupby('Province')['Wet_Month'].mean().round(1).sort_values(ascending=False)

print("\n AVERAGE NUMBER OF WET MONTHS PER YEAR (>50mm) ")
print(wet_counts_avg)

# Identify typical wet season months by province
print("\n TYPICAL WET SEASON PATTERNS ")
for province in sorted([p for p in provinces if p != 'Muchinga']):
    province_data = df_classified[df_classified['Province'] == province]
    wet_prob = province_data.groupby('Month')['Wet_Month'].mean() * 100
    wet_months = wet_prob[wet_prob > 50].index.tolist()
    if wet_months:
        print(f"{province:15s}: Wet season months: {wet_months}")
    else:
        print(f"{province:15s}: No clear wet season pattern")

# Time series

key_provinces = ['Lusaka', 'Northern', 'Western', 'Luapula', 'Southern']
key_provinces = [p for p in key_provinces if p in provinces]

if key_provinces:
    fig, axes = plt.subplots(len(key_provinces), 1, figsize=(14, 3 * len(key_provinces)))

    if len(key_provinces) == 1:
        axes = [axes]

    for idx, province in enumerate(key_provinces):
        province_data = df_classified[df_classified['Province'] == province].copy()

        # Create date column
        province_data['Date'] = pd.to_datetime(province_data['Year'].astype(str) + '-' +
                                               province_data['Month'].astype(str), format='%Y-%m')
        province_data = province_data.sort_values('Date')

        # Plot rainfall
        axes[idx].plot(province_data['Date'], province_data['rfq'],
                      color='steelblue', alpha=0.7, linewidth=1)

        # Add threshold line
        axes[idx].axhline(y=50, color='orange', linestyle='--', alpha=0.5, linewidth=1)

        # Color background by classification
        colors = {'Low': 'lightcoral', 'Normal': 'lightgreen', 'High': 'lightblue'}
        for i, row in province_data.iterrows():
            if i < len(province_data) - 1:
                axes[idx].axvspan(row['Date'],
                                  province_data.iloc[i+1]['Date'],
                                  alpha=0.2,
                                  color=colors.get(row['rainfall_class_monthly'], 'white'),
                                  zorder=0)

        axes[idx].set_title(f'{province} - Monthly Rainfall (1981-2026)', fontsize=12)
        axes[idx].set_ylabel('rfq (mm)')
        axes[idx].grid(True, alpha=0.3)
        axes[idx].set_xlim(province_data['Date'].min(), province_data['Date'].max())

    plt.tight_layout()
    plt.show()

# Summary

print("\n SUMMARY STATISTICS BY PROVINCE \n")
summary_by_province = df_classified[df_classified['Province'] != 'Muchinga'].groupby('Province').agg({
    'rfq': ['mean', 'std', 'min', 'max'],
    'rainfall_class_monthly': lambda x: (x == 'Low').sum() / len(x) * 100
}).round(2)

summary_by_province.columns = ['rfq_mean', 'rfq_std', 'rfq_min', 'rfq_max', 'pct_low']
summary_by_province = summary_by_province.sort_values('rfq_mean', ascending=False)

print(summary_by_province)

print("\n EXPLORATION COMPLETE!")
print("\nKey observations from the data:")
print(f"• Months: {list(monthly_stats.index)}")
print(f"• Wettest month average: {monthly_stats['mean'].max():.1f} mm (Month {monthly_stats['mean'].idxmax()})")
print(f"• Driest month average: {monthly_stats['mean'].min():.1f} mm (Month {monthly_stats['mean'].idxmin()})")
print("• Most variable month: Look at the CV heatmap")

# OCTOBER RAINFALL ANALYSIS BY PROVINCE

# Filter data for October only
october_data = df_classified[df_classified['Month'] == 10].copy()

# OCTOBER RAINFALL DISTRIBUTION BY PROVINCE

print(" OCTOBER RAINFALL STATISTICS BY PROVINCE \n")

october_stats = october_data.groupby('Province')['rfq'].agg([
    'count', 'mean', 'median', 'std', 'min', 'max'
]).round(2)

# Sort by mean rainfall
october_stats = october_stats.sort_values('mean', ascending=False)
print(october_stats)

# BOXPLOT: October rainfall by province

plt.figure(figsize=(14, 8))

# Boxplot
october_data.boxplot(column='rfq', by='Province', figsize=(14, 8))
plt.title('October Rainfall Distribution by Province', fontsize=14)
plt.suptitle('')  # Remove automatic title
plt.xlabel('Province', fontsize=12)
plt.ylabel('October Rainfall (mm)', fontsize=12)
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# BAR CHART: Mean October rainfall with error bars

plt.figure(figsize=(14, 8))

# Sort provinces by mean rainfall for better visualization
sorted_provinces = october_stats.index.tolist()
means = october_stats['mean'].values
stds = october_stats['std'].values

# Create color gradient based on rainfall amount
colors = plt.cm.Blues(means / means.max())

bars = plt.bar(range(len(sorted_provinces)), means, yerr=stds,
               capsize=5, color=colors, alpha=0.8, edgecolor='black')

plt.xticks(range(len(sorted_provinces)), sorted_provinces, rotation=45, ha='right')
plt.xlabel('Province', fontsize=12)
plt.ylabel('Mean October Rainfall (mm)', fontsize=12)
plt.title('Average October Rainfall by Province (±1 Std Dev)', fontsize=14)
plt.grid(True, alpha=0.3, axis='y')

# Add value labels on bars
for i, (province, mean_val) in enumerate(zip(sorted_provinces, means)):
    plt.text(i, mean_val + 5, f'{mean_val:.1f}', ha='center', fontsize=9)

plt.tight_layout()
plt.show()

# TIME SERIES: October rainfall trends by province

# Select key provinces for clearer visualization
key_provinces = ['Luapula', 'Northern', 'North-Western', 'Lusaka', 'Southern', 'Western']
october_key = october_data[october_data['Province'].isin(key_provinces)]

plt.figure(figsize=(15, 8))

for province in key_provinces:
    province_data = october_key[october_key['Province'] == province]
    plt.plot(province_data['Year'], province_data['rfq'],
             marker='o', markersize=4, linewidth=1.5, alpha=0.7,
             label=f'{province}')

plt.xlabel('Year', fontsize=12)
plt.ylabel('October Rainfall (mm)', fontsize=12)
plt.title('October Rainfall Trends by Province (1981-2026)', fontsize=14)
plt.legend(loc='upper right', fontsize=10)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# OCTOBER RAINFALL CLASSIFICATION

# Calculate October-specific thresholds
october_low = np.percentile(october_data['rfq'], 30)
october_high = np.percentile(october_data['rfq'], 70)

october_data['october_class'] = 'Normal'
october_data.loc[october_data['rfq'] < october_low, 'october_class'] = 'Low'
october_data.loc[october_data['rfq'] > october_high, 'october_class'] = 'High'

# Count classifications by province
october_class_summary = pd.crosstab(october_data['Province'], october_data['october_class'])
october_class_pct = october_class_summary.div(october_class_summary.sum(axis=1), axis=0) * 100

print("\n OCTOBER RAINFALL CLASSIFICATION (% of years) \n")
print(october_class_pct.round(1))

# Stacked bar chart
fig, ax = plt.subplots(figsize=(12, 6))
october_class_pct.sort_values('High', ascending=False).plot(
    kind='bar', stacked=True, ax=ax,
    color=['red', 'green', 'blue'], alpha=0.7
)

ax.set_title('October Rainfall Classification by Province', fontsize=14)
ax.set_xlabel('Province', fontsize=12)
ax.set_ylabel('Percentage of Years (%)', fontsize=12)
ax.legend(title='October Rainfall Class')
ax.grid(True, alpha=0.3, axis='y')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# HEATMAP: October rainfall over time

# Create a pivot table for heatmap
october_pivot = october_data.pivot_table(
    values='rfq',
    index='Year',
    columns='Province',
    aggfunc='mean'
)

plt.figure(figsize=(14, 10))
im = plt.imshow(october_pivot.values, aspect='auto', cmap='YlOrRd')

plt.colorbar(im, label='October Rainfall (mm)')
plt.xticks(range(len(october_pivot.columns)), october_pivot.columns, rotation=45, ha='right')
plt.yticks(range(0, len(october_pivot.index), 5), october_pivot.index[::5])
plt.xlabel('Province', fontsize=12)
plt.ylabel('Year', fontsize=12)
plt.title('October Rainfall Heatmap (1981-2026)', fontsize=14)

# Add grid lines
plt.axhline(y=0.5, color='black', linewidth=0.5)
plt.tight_layout()
plt.show()

# IDENTIFY EXTREME OCTOBER YEARS

print("\n EXTREME OCTOBER RAINFALL YEARS \n")

for province in sorted(october_data['Province'].unique()):
    province_oct = october_data[october_data['Province'] == province]

    if len(province_oct) > 0:
        # Top 3 wettest Octobers
        wettest = province_oct.nlargest(3, 'rfq')[['Year', 'rfq']]
        # Top 3 driest Octobers
        driest = province_oct.nsmallest(3, 'rfq')[['Year', 'rfq']]

        print(f"\n{province}:")
        print(f"  Wettest Octobers: {', '.join([f'{y} ({r:.1f}mm)' for y, r in zip(wettest['Year'], wettest['rfq'])])}")
        print(f"  Driest Octobers:  {', '.join([f'{y} ({r:.1f}mm)' for y, r in zip(driest['Year'], driest['rfq'])])}")

# OCTOBER RAINFALL VARIABILITY

# Calculate coefficient of variation for October
october_cv = october_data.groupby('Province')['rfq'].agg(
    lambda x: (x.std() / x.mean() * 100) if x.mean() > 0 else 0
).round(1).sort_values(ascending=False)

print("\n OCTOBER RAINFALL VARIABILITY (CV%) \n")
print(october_cv)

# Plot variability
plt.figure(figsize=(12, 6))
bars = plt.bar(october_cv.index, october_cv.values, color='coral', alpha=0.7)
plt.axhline(y=october_cv.mean(), color='red', linestyle='--',
            label=f'Average CV = {october_cv.mean():.1f}%')
plt.xlabel('Province', fontsize=12)
plt.ylabel('Coefficient of Variation (%)', fontsize=12)
plt.title('October Rainfall Variability by Province', fontsize=14)
plt.xticks(rotation=45)
plt.legend()
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()

# SUMMARY TABLE FOR REPORT

print("\n SUMMARY: OCTOBER RAINFALL INSIGHTS \n")

# Find wettest and driest provinces
wettest_oct = october_stats.iloc[0]
driest_oct = october_stats.iloc[-1]

print(f"Wettest October province: {wettest_oct.name} ({wettest_oct['mean']:.1f} mm average)")
print(f"Driest October province: {driest_oct.name} ({driest_oct['mean']:.1f} mm average)")
print(f"National October average: {october_stats['mean'].mean():.1f} mm")
print(f"Most variable October: {october_cv.index[0]} (CV = {october_cv.iloc[0]:.1f}%)")
print(f"Least variable October: {october_cv.index[-1]} (CV = {october_cv.iloc[-1]:.1f}%)")

# Create a more detailed summary table
summary_october = pd.DataFrame({
    'Mean (mm)': october_stats['mean'],
    'CV (%)': october_cv,
    '% Low Octobers': october_class_pct['Low'],
    '% High Octobers': october_class_pct['High']
}).round(1)

print("\n=== DETAILED OCTOBER SUMMARY ===\n")
print(summary_october.sort_values('Mean (mm)', ascending=False))

# OCTOBER RAINFALL TREND ANALYSIS

# Filter data for October only
october_data = df_classified[df_classified['Month'] == 10].copy()

# How October has changed

# Create decade column
october_data['Decade'] = pd.cut(october_data['Year'],
                                 bins=[1980, 1990, 2000, 2010, 2020, 2030],
                                 labels=['1980s', '1990s', '2000s', '2010s', '2020s'])

# Calculate statistics by decade
decade_stats = october_data.groupby(['Province', 'Decade'])['rfq'].agg([
    'mean', 'std', 'count'
]).round(2).reset_index()

print("=== OCTOBER RAINFALL BY DECADE ===\n")
for province in sorted(october_data['Province'].unique()):
    province_decade = decade_stats[decade_stats['Province'] == province]
    if len(province_decade) > 0:
        print(f"\n{province}:")
        for _, row in province_decade.iterrows():
            print(f"  {row['Decade']}: {row['mean']:.1f} mm (±{row['std']:.1f})")

# TIME SERIES WITH TREND LINES

fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# Plot 1: National average October rainfall over time
national_october = october_data.groupby('Year')['rfq'].mean().reset_index()

axes[0,0].plot(national_october['Year'], national_october['rfq'],
               marker='o', markersize=4, linewidth=1.5, color='blue', alpha=0.7)
axes[0,0].set_xlabel('Year', fontsize=12)
axes[0,0].set_ylabel('National Average October Rainfall (mm)', fontsize=12)
axes[0,0].set_title('National October Rainfall Trend (1981-2026)', fontsize=14)
axes[0,0].grid(True, alpha=0.3)

# Add trend line
z = np.polyfit(national_october['Year'], national_october['rfq'], 1)
p = np.poly1d(z)
axes[0,0].plot(national_october['Year'], p(national_october['Year']),
               color='red', linestyle='--', linewidth=2,
               label=f'Trend: {z[0]:.2f} mm/year')
axes[0,0].legend()
axes[0,0].axhline(y=national_october['rfq'].mean(), color='gray', linestyle=':', alpha=0.5)

# Plot 2: Rolling average (10-year) to see trend clearly
rolling_avg = national_october.set_index('Year')['rfq'].rolling(window=10, center=True).mean()

axes[0,1].plot(national_october['Year'], national_october['rfq'],
               color='lightblue', alpha=0.5, linewidth=1, label='Annual')
axes[0,1].plot(rolling_avg.index, rolling_avg.values,
               color='darkblue', linewidth=2, label='10-Year Rolling Average')
axes[0,1].set_xlabel('Year', fontsize=12)
axes[0,1].set_ylabel('National Average October Rainfall (mm)', fontsize=12)
axes[0,1].set_title('October Rainfall: 10-Year Rolling Average', fontsize=14)
axes[0,1].legend()
axes[0,1].grid(True, alpha=0.3)

# Plot 3: Key provinces with trend lines
key_provinces = ['Lusaka', 'Southern', 'Luapula', 'Northern']
colors = {'Lusaka': 'red', 'Southern': 'orange', 'Luapula': 'green', 'Northern': 'blue'}

for province in key_provinces:
    province_data = october_data[october_data['Province'] == province]
    province_annual = province_data.groupby('Year')['rfq'].mean().reset_index()

    axes[1,0].plot(province_annual['Year'], province_annual['rfq'],
                   marker='o', markersize=3, linewidth=1, alpha=0.6,
                   label=province, color=colors[province])

    # Add trend line
    z = np.polyfit(province_annual['Year'], province_annual['rfq'], 1)
    p = np.poly1d(z)
    axes[1,0].plot(province_annual['Year'], p(province_annual['Year']),
                   linestyle='--', linewidth=2, color=colors[province],
                   label=f'{province} trend ({z[0]:.1f} mm/yr)')

axes[1,0].set_xlabel('Year', fontsize=12)
axes[1,0].set_ylabel('October Rainfall (mm)', fontsize=12)
axes[1,0].set_title('October Rainfall Trends by Province', fontsize=14)
axes[1,0].legend(loc='upper right', fontsize=8)
axes[1,0].grid(True, alpha=0.3)

# Plot 4: Pre-2000 vs Post-2000 comparison
october_data['Period'] = october_data['Year'].apply(lambda x: '1981-2000' if x <= 2000 else '2001-2026')

period_comparison = october_data.groupby(['Province', 'Period'])['rfq'].mean().unstack()
period_comparison['Change'] = period_comparison['2001-2026'] - period_comparison['1981-2000']
period_comparison = period_comparison.sort_values('Change')

# Bar chart of changes
change_colors = ['red' if x < 0 else 'green' for x in period_comparison['Change']]
bars = axes[1,1].barh(period_comparison.index, period_comparison['Change'], color=change_colors, alpha=0.7)
axes[1,1].axvline(x=0, color='black', linewidth=1)
axes[1,1].set_xlabel('Change in October Rainfall (mm)', fontsize=12)
axes[1,1].set_title('Change in October Rainfall: 2001-2026 vs 1981-2000', fontsize=14)
axes[1,1].grid(True, alpha=0.3, axis='x')

# Add value labels
for i, (province, change) in enumerate(period_comparison['Change'].items()):
    axes[1,1].text(change + (1 if change >= 0 else -3), i,
                   f'{change:+.1f} mm', va='center', fontsize=9)

plt.tight_layout()
plt.show()

# Is the decline significant?

from scipy import stats

print("\n STATISTICAL ANALYSIS: OCTOBER RAINFALL CHANGE \n")

for province in key_provinces:
    province_data = october_data[october_data['Province'] == province]
    before = province_data[province_data['Year'] <= 2000]['rfq']
    after = province_data[province_data['Year'] > 2000]['rfq']

    if len(before) > 5 and len(after) > 5:
        t_stat, p_value = stats.ttest_ind(before, after)
        mean_change = after.mean() - before.mean()

        print(f"\n{province}:")
        print(f"  1981-2000 mean: {before.mean():.1f} mm")
        print(f"  2001-2026 mean: {after.mean():.1f} mm")
        print(f"  Change: {mean_change:+.1f} mm ({mean_change/before.mean()*100:+.1f}%)")
        print(f"  p-value: {p_value:.4f} {'(SIGNIFICANT)' if p_value < 0.05 else '(not significant)'}")

# TREND BY PROVINCE (Linear regression)

print("\n LINEAR TREND ANALYSIS (mm/year) \n")

trend_results = []

for province in sorted(october_data['Province'].unique()):
    province_data = october_data[october_data['Province'] == province]
    province_annual = province_data.groupby('Year')['rfq'].mean().reset_index()

    if len(province_annual) > 10:
        slope, intercept, r_value, p_value, std_err = stats.linregress(province_annual['Year'], province_annual['rfq'])

        trend_results.append({
            'Province': province,
            'Trend_mm_per_year': slope,
            'R_squared': r_value**2,
            'P_value': p_value,
            'Significant': p_value < 0.05
        })

        print(f"{province:15s}: {slope:+.2f} mm/year  (R²={r_value**2:.3f}, p={p_value:.4f})")

trend_df = pd.DataFrame(trend_results).sort_values('Trend_mm_per_year')

# Plot trends
plt.figure(figsize=(12, 6))
colors = ['red' if x < 0 else 'green' for x in trend_df['Trend_mm_per_year']]
plt.barh(trend_df['Province'], trend_df['Trend_mm_per_year'], color=colors, alpha=0.7)
plt.axvline(x=0, color='black', linewidth=1)
plt.xlabel('Trend (mm/year)', fontsize=12)
plt.title('October Rainfall Trends by Province', fontsize=14)
plt.grid(True, alpha=0.3, axis='x')
plt.tight_layout()
plt.show()


# When did October change?

print("\n DETECTING SHIFT IN OCTOBER RAINFALL \n")

# Use cumulative sum to detect change point
for province in key_provinces:
    province_data = october_data[october_data['Province'] == province]
    province_annual = province_data.groupby('Year')['rfq'].mean().reset_index()
    province_annual = province_annual.sort_values('Year')

    # Calculate cumulative deviation from mean
    mean_val = province_annual['rfq'].mean()
    province_annual['cum_dev'] = (province_annual['rfq'] - mean_val).cumsum()

    # Find max deviation point
    max_dev_year = province_annual.loc[province_annual['cum_dev'].idxmax(), 'Year']

    plt.figure(figsize=(10, 4))
    plt.plot(province_annual['Year'], province_annual['cum_dev'], marker='o', markersize=3)
    plt.axvline(x=max_dev_year, color='red', linestyle='--', label=f'Shift point: ~{max_dev_year}')
    plt.xlabel('Year')
    plt.ylabel('Cumulative Deviation from Mean')
    plt.title(f'{province}: October Rainfall Shift Detection')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

    print(f"{province}: Most likely shift around {max_dev_year}")

# FREQUENCY OF LOW OCTOBER RAINS BY DECADE

# Define "low October" as below 70mm (critical threshold for planting)
october_data['Low_October'] = october_data['rfq'] < 70

# Calculate frequency by decade
low_frequency = october_data.groupby(['Province', 'Decade'])['Low_October'].mean() * 100
low_frequency = low_frequency.reset_index()

# Pivot for heatmap
low_pivot = low_frequency.pivot(index='Province', columns='Decade', values='Low_October')

plt.figure(figsize=(12, 8))
im = plt.imshow(low_pivot.values, aspect='auto', cmap='YlOrRd', vmin=0, vmax=100)
plt.colorbar(im, label='% of Years with Low October Rain (<70mm)')
plt.xticks(range(len(low_pivot.columns)), low_pivot.columns)
plt.yticks(range(len(low_pivot.index)), low_pivot.index)
plt.title('Frequency of Low October Rainfall by Decade', fontsize=14)
plt.xlabel('Decade', fontsize=12)
plt.ylabel('Province', fontsize=12)

# Add text annotations
for i in range(len(low_pivot.index)):
    for j in range(len(low_pivot.columns)):
        if not pd.isna(low_pivot.iloc[i, j]):
            plt.text(j, i, f'{low_pivot.iloc[i, j]:.0f}%',
                    ha='center', va='center', color='white' if low_pivot.iloc[i, j] > 50 else 'black')

plt.tight_layout()
plt.show()

print("\n LOW OCTOBER RAIN FREQUENCY (%) \n")
print(low_pivot.round(1))

# THE SHIFT IN OCTOBER RAINFALL

print("\n SUMMARY: OCTOBER RAINFALL SHIFT \n")

# Calculate overall change
overall_before = october_data[october_data['Year'] <= 2000]['rfq'].mean()
overall_after = october_data[october_data['Year'] > 2000]['rfq'].mean()

print(f"NATIONAL OCTOBER RAINFALL:")
print(f"  1981-2000 average: {overall_before:.1f} mm")
print(f"  2001-2026 average: {overall_after:.1f} mm")
print(f"  CHANGE: {overall_after - overall_before:+.1f} mm ({(overall_after - overall_before)/overall_before*100:+.1f}%)")

print("\nPROVINCES WITH SIGNIFICANT DECLINE:")
declining = trend_df[trend_df['Trend_mm_per_year'] < -0.5]
for _, row in declining.iterrows():
    print(f"  {row['Province']}: {row['Trend_mm_per_year']:.2f} mm/year decline (p={row['P_value']:.3f})")

print("\nPROVINCES WITH INCREASING OCTOBER RAIN:")
increasing = trend_df[trend_df['Trend_mm_per_year'] > 0.5]
for _, row in increasing.iterrows():
    print(f"  {row['Province']}: {row['Trend_mm_per_year']:.2f} mm/year increase (p={row['P_value']:.3f})")

print("\nCRITICAL INSIGHT:")
print("If October rainfall has declined, the traditional planting window may no longer be reliable.")
print("Farmers may need to:")
print("  • Delay planting until November/December")
print("  • Use drought-tolerant varieties")
print("  • Consider supplemental irrigation for early season")

#full rainfall analysis for all 6 months