# -*- coding: utf-8 -*-
"""Rainfall and yield analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w5MYRhhsIgVPHGVRZ_meOwHprwMWBbv7

Import Data
"""

# Install, import, load and prepare data
!pip install gspread pandas

from google.colab import auth
from google.auth import default
import gspread
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Authenticate and load from Google Sheets
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

worksheet = gc.open('Final_rainfall_and_yield_data').sheet1
data = worksheet.get_all_values()
df = pd.DataFrame(data[1:], columns=data[0])

"""Exploratory, Trend, Correlation, Regression Analysis"""

#  DATA PREPARATION

# Clean and rename columns
df = df.rename(columns={
    'province': 'Province',
    'year': 'Year',
    'seasonal rainfall total(mm)': 'Rainfall_mm',
    'yield': 'Yield_t_ha'
})

# Convert to numeric
numeric_cols = ['Year', 'Rainfall_mm', 'Yield_t_ha']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Drop rows with missing values
df = df.dropna(subset=['Province', 'Year', 'Yield_t_ha'])
df['Year'] = df['Year'].astype(int)

# Filter out rows with zero yield (likely missing data)
df = df[df['Yield_t_ha'] > 0]

# Create analysis dataset (including Muchinga)
df_analysis = df.copy()

# Verify data structure
print("DATA LOADED SUCCESSFULLY")
print(f"Total rows: {df_analysis.shape[0]}")
print(f"Years: {df_analysis['Year'].min()} - {df_analysis['Year'].max()}")
print(f"Provinces: {sorted(df_analysis['Province'].unique())}")
print(f"Rainfall range: {df_analysis['Rainfall_mm'].min():.0f} - {df_analysis['Rainfall_mm'].max():.0f} mm")
print(f"Yield range: {df_analysis['Yield_t_ha'].min():.2f} - {df_analysis['Yield_t_ha'].max():.2f} t/ha")

print("\nPROVINCE BREAKDOWN")
for province in sorted(df_analysis['Province'].unique()):
    province_data = df_analysis[df_analysis['Province'] == province]
    years = sorted(province_data['Year'].unique())
    print(f"{province}: {len(province_data)} records, {len(years)} unique years ({min(years)}-{max(years)})")

print("EXPLORATORY DATA ANALYSIS")

# Overall summary statistics
print("\nOVERALL SUMMARY STATISTICS")
print(f"Rainfall (mm): mean={df_analysis['Rainfall_mm'].mean():.1f}, median={df_analysis['Rainfall_mm'].median():.1f}, min={df_analysis['Rainfall_mm'].min():.1f}, max={df_analysis['Rainfall_mm'].max():.1f}")
print(f"Yield (t/ha): mean={df_analysis['Yield_t_ha'].mean():.2f}, median={df_analysis['Yield_t_ha'].median():.2f}, min={df_analysis['Yield_t_ha'].min():.2f}, max={df_analysis['Yield_t_ha'].max():.2f}")

# Summary by province
print("\nSUMMARY BY PROVINCE")
province_summary = df_analysis.groupby('Province').agg({
    'Rainfall_mm': ['mean', 'min', 'max', 'std'],
    'Yield_t_ha': ['mean', 'min', 'max', 'std']
}).round(2)
province_summary.columns = ['_'.join(col).strip() for col in province_summary.columns]
print(province_summary)

# Distribution plots
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

df_analysis['Rainfall_mm'].hist(bins=20, ax=axes[0,0], color='steelblue', edgecolor='black')
axes[0,0].set_title('Rainfall Distribution - All Provinces')
axes[0,0].set_xlabel('Rainfall (mm)')
axes[0,0].set_ylabel('Frequency')

df_analysis['Yield_t_ha'].hist(bins=20, ax=axes[0,1], color='forestgreen', edgecolor='black')
axes[0,1].set_title('Yield Distribution - All Provinces')
axes[0,1].set_xlabel('Yield (t/ha)')
axes[0,1].set_ylabel('Frequency')

df_analysis.boxplot(column='Rainfall_mm', by='Province', ax=axes[1,0], rot=45)
axes[1,0].set_title('Rainfall Distribution by Province')
axes[1,0].set_xlabel('Province')
axes[1,0].set_ylabel('Rainfall (mm)')

df_analysis.boxplot(column='Yield_t_ha', by='Province', ax=axes[1,1], rot=45)
axes[1,1].set_title('Yield Distribution by Province')
axes[1,1].set_xlabel('Province')
axes[1,1].set_ylabel('Yield (t/ha)')

plt.suptitle('')
plt.tight_layout()
plt.show()

# Trend Analysis

print("TREND ANALYSIS")

# Yearly trends (national averages)
yearly_national = df_analysis.groupby('Year').agg({
    'Rainfall_mm': 'mean',
    'Yield_t_ha': 'mean'
}).reset_index()

fig, axes = plt.subplots(2, 2, figsize=(15, 10))

axes[0,0].plot(yearly_national['Year'], yearly_national['Rainfall_mm'], 'o-', color='steelblue', linewidth=1, markersize=4)
axes[0,0].set_title('National Average Rainfall Over Time')
axes[0,0].set_xlabel('Year')
axes[0,0].set_ylabel('Rainfall (mm)')
axes[0,0].grid(True, alpha=0.3)

axes[0,1].plot(yearly_national['Year'], yearly_national['Yield_t_ha'], 'o-', color='forestgreen', linewidth=1, markersize=4)
axes[0,1].set_title('National Average Yield Over Time')
axes[0,1].set_xlabel('Year')
axes[0,1].set_ylabel('Yield (t/ha)')
axes[0,1].grid(True, alpha=0.3)

for province in sorted(df_analysis['Province'].unique()):
    province_data = df_analysis[df_analysis['Province'] == province]
    axes[1,0].plot(province_data['Year'], province_data['Yield_t_ha'], 'o-', label=province, linewidth=0.8, markersize=3)
axes[1,0].set_title('Yield Trends by Province')
axes[1,0].set_xlabel('Year')
axes[1,0].set_ylabel('Yield (t/ha)')
axes[1,0].legend(loc='best', fontsize=8)
axes[1,0].grid(True, alpha=0.3)

# Rainfall vs yield scatter over time
scatter = axes[1,1].scatter(df_analysis['Year'], df_analysis['Yield_t_ha'],
                            c=df_analysis['Rainfall_mm'], cmap='RdYlBu', alpha=0.6, s=50)
axes[1,1].set_title('Yield Over Time (color = rainfall)')
axes[1,1].set_xlabel('Year')
axes[1,1].set_ylabel('Yield (t/ha)')
plt.colorbar(scatter, ax=axes[1,1], label='Rainfall (mm)')
axes[1,1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print("\nTREND SUMMARY")
print(f"National rainfall mean: {yearly_national['Rainfall_mm'].mean():.0f} mm")
print(f"National yield mean: {yearly_national['Yield_t_ha'].mean():.2f} t/ha")

# CORRELATION ANALYSIS

print("CORRELATION ANALYSIS")

# Overall correlation
corr_rain_yield = df_analysis['Rainfall_mm'].corr(df_analysis['Yield_t_ha'])
print(f"Overall Rainfall-Yield correlation: {corr_rain_yield:.3f}")

# Correlation by province
print("\nCORRELATION BY PROVINCE")

corr_by_province = df_analysis.groupby('Province').apply(
    lambda x: x['Rainfall_mm'].corr(x['Yield_t_ha'])).round(3)
for province, corr in corr_by_province.items():
    print(f"{province}: {corr}")

# Visualize relationship
fig, axes = plt.subplots(1, 2, figsize=(15, 6))

axes[0].scatter(df_analysis['Rainfall_mm'], df_analysis['Yield_t_ha'], alpha=0.5, s=30)
axes[0].set_xlabel('Rainfall (mm)')
axes[0].set_ylabel('Yield (t/ha)')
axes[0].set_title('Rainfall vs Yield - All Provinces Combined')
z = np.polyfit(df_analysis['Rainfall_mm'], df_analysis['Yield_t_ha'], 1)
p = np.poly1d(z)
axes[0].plot(sorted(df_analysis['Rainfall_mm']), p(sorted(df_analysis['Rainfall_mm'])), 'r-', linewidth=2)
axes[0].grid(True, alpha=0.3)

provinces = sorted(df_analysis['Province'].unique())
colors = plt.cm.tab20(np.linspace(0, 1, len(provinces)))

for i, province in enumerate(provinces):
    prov_data = df_analysis[df_analysis['Province'] == province]
    axes[1].scatter(prov_data['Rainfall_mm'], prov_data['Yield_t_ha'],
                   color=colors[i], label=province, alpha=0.6, s=30)
axes[1].set_xlabel('Rainfall (mm)')
axes[1].set_ylabel('Yield (t/ha)')
axes[1].set_title('Rainfall vs Yield - Colored by Province')
axes[1].legend(loc='best', fontsize=8)
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print("RAINFALL EFFICIENCY (Yield per 100mm rainfall)")

df_analysis['Rain_efficiency'] = df_analysis['Yield_t_ha'] / (df_analysis['Rainfall_mm'] / 100)
efficiency_all = df_analysis.groupby('Province')['Rain_efficiency'].agg(['mean', 'std', 'min', 'max'])
efficiency_all = efficiency_all.sort_values('mean', ascending=False)

print(efficiency_all.round(3))

plt.figure(figsize=(12, 6))
colors_efficiency = plt.cm.RdYlGn(np.linspace(0.3, 0.9, len(efficiency_all)))
bars = plt.bar(efficiency_all.index, efficiency_all['mean'], color=colors_efficiency)
plt.errorbar(efficiency_all.index, efficiency_all['mean'], yerr=efficiency_all['std'],
            fmt='none', color='black', capsize=5)
plt.title('Rainfall Efficiency by Province', fontsize=14)
plt.xlabel('Province')
plt.ylabel('Yield per 100mm rain (t/ha)')
plt.axhline(y=efficiency_all['mean'].mean(), color='red', linestyle='--',
           alpha=0.5, label=f'National average ({efficiency_all["mean"].mean():.3f} t/ha/100mm)')
plt.legend()
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()

print(f"\nMost efficient: {efficiency_all.index[0]} ({efficiency_all.iloc[0]['mean']:.3f} t/ha/100mm)")
print(f"Least efficient: {efficiency_all.index[-1]} ({efficiency_all.iloc[-1]['mean']:.3f} t/ha/100mm)")

# OPTIMAL RAINFALL RANGE

print("OPTIMAL RAINFALL RANGE ANALYSIS")

print("\nRAINFALL DISTRIBUTION SUMMARY")
print("-" * 50)
print(df_analysis['Rainfall_mm'].describe())

# Create bins
df_analysis['Rain_bin'] = pd.cut(df_analysis['Rainfall_mm'],
    bins=[0, 800, 1000, 1200, 1400, 1600, 1800, 2500],
    labels=['<800', '800-1000', '1000-1200', '1200-1400', '1400-1600', '1600-1800', '>1800'])

bin_summary = df_analysis.groupby('Rain_bin', observed=False)['Yield_t_ha'].agg(['mean', 'std', 'count'])
print("\nAVERAGE YIELD BY RAINFALL RANGE")
print("-" * 50)
print(bin_summary.round(3))

# Visualize
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

axes[0].bar(bin_summary.index, bin_summary['mean'],
           color=plt.cm.RdYlGn_r(np.linspace(0.2, 0.8, len(bin_summary))),
           alpha=0.8, yerr=bin_summary['std'], capsize=5)
axes[0].axhline(y=df_analysis['Yield_t_ha'].mean(), color='red', linestyle='--',
               label=f'Overall average ({df_analysis["Yield_t_ha"].mean():.2f} t/ha)')
axes[0].set_title('Yield by Rainfall Range')
axes[0].set_xlabel('Rainfall Range (mm)')
axes[0].set_ylabel('Average Yield (t/ha)')
axes[0].legend()
axes[0].grid(True, alpha=0.3, axis='y')
axes[0].tick_params(axis='x', rotation=45)

axes[1].pie(bin_summary['count'], labels=bin_summary.index, autopct='%1.1f%%',
           colors=plt.cm.RdYlGn_r(np.linspace(0.2, 0.8, len(bin_summary))))
axes[1].set_title('Distribution of Observations by Rainfall Range')

plt.tight_layout()
plt.show()

# Find optimal range
valid_bins = bin_summary[bin_summary['count'] >= 5]
if len(valid_bins) > 0:
    optimal = valid_bins['mean'].idxmax()
    print(f"\nOPTIMAL RANGE: {optimal} mm")
    print(f"Average yield in optimal range: {valid_bins.loc[optimal, 'mean']:.2f} t/ha")
    print(f"Observations in optimal range: {valid_bins.loc[optimal, 'count']:.0f}")

# REGRESSION ANALYSIS

print("REGRESSION ANALYSIS")

import statsmodels.api as sm

# Linear model
X = sm.add_constant(df_analysis['Rainfall_mm'])
y = df_analysis['Yield_t_ha']
model = sm.OLS(y, X).fit()

# Quadratic model
df_analysis['Rainfall_sq'] = df_analysis['Rainfall_mm']**2
X2 = sm.add_constant(df_analysis[['Rainfall_mm', 'Rainfall_sq']])
model2 = sm.OLS(y, X2).fit()

print(f"Linear model R²: {model.rsquared:.3f}")
print(f"Quadratic model R²: {model2.rsquared:.3f}")

print("\nMODEL COEFFICIENTS")
print("Linear model:")
print(f"  Intercept: {model.params.iloc[0]:.4f}")
print(f"  Rainfall coefficient: {model.params.iloc[1]:.6f}")
print("\nQuadratic model:")
print(f"  Intercept: {model2.params.iloc[0]:.4f}")
print(f"  Rainfall: {model2.params.iloc[1]:.6f}")
print(f"  Rainfall²: {model2.params.iloc[2]:.8f}")

# Model by province
print("\nMODEL BY PROVINCE")
print("-" * 40)
province_models = []
for province in sorted(df_analysis['Province'].unique()):
    prov_data = df_analysis[df_analysis['Province'] == province]
    if len(prov_data) > 5:
        X_prov = sm.add_constant(prov_data['Rainfall_mm'])
        y_prov = prov_data['Yield_t_ha']
        prov_model = sm.OLS(y_prov, X_prov).fit()
        province_models.append({
            'Province': province,
            'R²': prov_model.rsquared,
            'Coefficient': prov_model.params.iloc[1],
            'P-value': prov_model.pvalues.iloc[1]
        })

prov_model_df = pd.DataFrame(province_models).round(3)
print(prov_model_df.to_string(index=False))

# Visualize
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].scatter(df_analysis['Rainfall_mm'], df_analysis['Yield_t_ha'], alpha=0.3, s=20)
# Add binned averages
x_sorted = np.sort(df_analysis['Rainfall_mm'].unique())
y_mean = df_analysis.groupby('Rainfall_mm')['Yield_t_ha'].mean()
axes[0].plot(y_mean.index, y_mean.values, 'r-', linewidth=2, label='Average by rainfall')
axes[0].set_xlabel('Rainfall (mm)')
axes[0].set_ylabel('Yield (t/ha)')
axes[0].set_title(f'Rainfall vs Yield (R² = {model.rsquared:.3f})')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Residuals plot
residuals = model.resid
axes[1].scatter(model.fittedvalues, residuals, alpha=0.5, s=20)
axes[1].axhline(y=0, color='r', linestyle='--')
axes[1].set_xlabel('Fitted values')
axes[1].set_ylabel('Residuals')
axes[1].set_title('Residual Plot')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# DROUGHT VULNERABILITY

print("DROUGHT VULNERABILITY ANALYSIS")

# Define drought threshold (25th percentile)
drought_threshold = df_analysis['Rainfall_mm'].quantile(0.25)
print(f"Drought threshold (bottom 25%): ≤ {drought_threshold:.0f} mm")

# Count low rainfall years by province
low_rain_provinces = df_analysis[df_analysis['Rainfall_mm'] <= drought_threshold].groupby('Province').size()
low_rain_provinces = low_rain_provinces.sort_values(ascending=False)

print("\nLOW RAINFALL YEARS BY PROVINCE")
print("-" * 40)
for province, count in low_rain_provinces.items():
    print(f"{province}: {count} years")

plt.figure(figsize=(12, 6))
colors_risk = plt.cm.RdYlBu_r(np.linspace(0.2, 0.9, len(low_rain_provinces)))
bars = plt.bar(low_rain_provinces.index, low_rain_provinces.values, color=colors_risk)
plt.axhline(y=low_rain_provinces.mean(), color='navy', linestyle='--',
           label=f'Average ({low_rain_provinces.mean():.1f} years)')
plt.title('Low Rainfall Years by Province')
plt.xlabel('Province')
plt.ylabel('Number of years')
plt.legend()
plt.grid(True, alpha=0.3, axis='y')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Yield performance in drought years
print("\nYIELD IN DROUGHT YEARS VS NORMAL YEARS")
print("-" * 50)
drought_yields = df_analysis[df_analysis['Rainfall_mm'] <= drought_threshold]['Yield_t_ha']
normal_yields = df_analysis[df_analysis['Rainfall_mm'] > drought_threshold]['Yield_t_ha']

print(f"Drought years (n={len(drought_yields)}): mean yield = {drought_yields.mean():.2f} t/ha")
print(f"Normal years (n={len(normal_yields)}): mean yield = {normal_yields.mean():.2f} t/ha")
print(f"Yield reduction: {(1 - drought_yields.mean()/normal_yields.mean())*100:.1f}%")

# MUCHINGA PROVINCE ANALYSIS

print("\n" + "=" * 60)
print("MUCHINGA PROVINCE ANALYSIS")
print("=" * 60)

muchinga_data = df_analysis[df_analysis['Province'] == 'Muchinga']
print(f"Muchinga records: {len(muchinga_data)}")
if len(muchinga_data) > 0:
    print(f"Muchinga years: {muchinga_data['Year'].min()} - {muchinga_data['Year'].max()}")
    print(f"Muchinga rainfall: mean={muchinga_data['Rainfall_mm'].mean():.0f} mm, range={muchinga_data['Rainfall_mm'].min():.0f}-{muchinga_data['Rainfall_mm'].max():.0f} mm")
    print(f"Muchinga yield: mean={muchinga_data['Yield_t_ha'].mean():.2f} t/ha, range={muchinga_data['Yield_t_ha'].min():.2f}-{muchinga_data['Yield_t_ha'].max():.2f} t/ha")

    # Compare Muchinga with other provinces
    other_provinces = df_analysis[df_analysis['Province'] != 'Muchinga']
    print(f"\nComparison with other provinces (n={len(other_provinces)}):")
    print(f"  Rainfall: Muchinga {muchinga_data['Rainfall_mm'].mean():.0f} mm vs Others {other_provinces['Rainfall_mm'].mean():.0f} mm")
    print(f"  Yield: Muchinga {muchinga_data['Yield_t_ha'].mean():.2f} t/ha vs Others {other_provinces['Yield_t_ha'].mean():.2f} t/ha")

print("\n" + "=" * 60)
print("ANALYSIS COMPLETE")
print("=" * 60)